<?php

/**
 * Place
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property string $accesability
 * @property enum $state
 * @property integer $address_id
 * @property integer $schedule_id
 * @property integer $group_id
 * @property integer $contact_gr_id
 * @property  $
 * @property Contact $
 * @property PlaceSchedule $
 * @property PlaceGroup $
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Place extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('places');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('accesability', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('state', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'open',
              1 => 'closed',
              2 => 'vacation',
             ),
             ));
        $this->hasColumn('address_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('schedule_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('group_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('contact_gr_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Address');

        $this->hasOne('Contact', array(
             'foreign' => 'gr_id',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasOne('PlaceSchedule', array(
             'local' => 'schedule_id'));

        $this->hasOne('PlaceGroup', array(
             'local' => 'group_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'description',
              1 => 'accesability',
             ),
             ));
        $searchable0 = new Doctrine_Template_Searchable(array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'description',
             ),
             ));
        $blameable0 = new Doctrine_Template_Blameable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $publishable0 = new Doctrine_Template_Publishable();
        $nestedset0 = new Doctrine_Template_NestedSet();
        $this->actAs($sluggable0);
        $this->actAs($i18n0);
        $this->actAs($searchable0);
        $this->actAs($blameable0);
        $this->actAs($softdelete0);
        $this->actAs($timestampable0);
        $this->actAs($publishable0);
        $this->actAs($nestedset0);
    }
}